version: '3.1'

services:

  geoserver:
    image: docker.osgeo.org/geoserver:2.24.x
    container_name: geoserver
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - geoserver:/opt/geoserver_data

  posgres_db:
    image: postgis/postgis
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: geoserver
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres:/var/lib/postgresql/data
 
volumes:
   postgres:
   geoserver:

