version: '3.1'

services:

  geoserver:
    image: docker.osgeo.org/geoserver:2.24.x
    container_name: geoserver
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - geoserver:/opt/geoserver_data

volumes:
   geoserver:

